name: Notificar por Correo en Push a la Rama main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Enviar Notificación por Correo usando SendGrid
        run: |
          curl -X POST https://api.sendgrid.com/v3/mail/send \
          -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
                "personalizations": [
                  {
                    "to": [{"email": "luis.flores@idslatam.com"}],
                    "subject": "Notificación de Push en la Rama main"
                  }
                ],
                "from": {"email": "teseo@idslatam.com"},
                "content": [{"type": "text/plain", "value": "Se ha realizado un push en la rama main del repositorio $GITHUB_REPOSITORY"}]
              }'
